'''Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do 
not exceed four million, find the sum of the even-valued terms.'''

from math_functions import fib

def main():
    """ () -> int
    Runs the main function which will produce the answer to the problem
    """
    n = 1
    fib_val = fib(n)
    result = 0

    while fib_val < 4000000:
        if fib_val % 2 == 0:
            result += fib_val
        n += 1
        fib_val = fib(n)
    return result

print(main())